###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: mailhog
      ports:
        - "1026:8025"

    db:
      image: mysql:5.7
      container_name: db
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=banco
        - MYSQL_USER=banco
        - MYSQL_PASSWORD=banco
      ports:
        - "1027:3306"
      networks:
        - default

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      environment:
        MYSQL_USER: banco
        MYSQL_PASSWORD: banco
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: db
      restart: always
      depends_on:
        - db
      links:
        - db
      ports:
        - 8000:80

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

